name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '2.6.8'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: default
        bundler-cache: true
    - name: Install libcurl4-openssl-dev
      run: sudo apt-get install -y libcurl4-openssl-dev
    - name: Run the default task
      run: bundle exec rake
